"""
AIAAM Translator - Mode B (Selective Review)

Pipeline:
1. Fetch README/model card/package metadata from source
2. Haiku 4.5 produces MAI-1 draft
3. Validator inspects critical fields
4. If any critical field is null/malformed → Sonnet 4.6 fixes ONLY those fields
5. Final MAI-1 saved to DB

Sources supported:
- github.com → translate_readme (LLM)
- huggingface.co → translate_model_card (LLM, variant prompt)
- pypi.org → translate_package_metadata (direct mapping, no LLM)
- npmjs.com → translate_package_metadata (direct mapping, no LLM)
"""
import os
import json
import re
import time
from typing import Optional, Tuple
from urllib.parse import urlparse

import httpx
from anthropic import Anthropic
from dotenv import load_dotenv

from models import Tool

load_dotenv()

# Configuration
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
HF_TOKEN = os.getenv("HF_TOKEN")
MODEL_PRIMARY = os.getenv("TRANSLATOR_MODEL_PRIMARY", "claude-haiku-4-5-20251001")
MODEL_REVIEWER = os.getenv("TRANSLATOR_MODEL_REVIEWER", "claude-sonnet-4-6")

client = Anthropic(api_key=ANTHROPIC_API_KEY) if ANTHROPIC_API_KEY else None


# =====================================================================
# PROMPTS — Strict JSON output, declarative, deterministic
# =====================================================================

PROMPT_GITHUB_README = """ROLE: JSON converter. Input: raw README text. Output: MAI-1 object.

STRICT RULES:
- Output ONLY a single valid JSON object. No markdown. No explanation. No code fences.
- Never invent data. If a field cannot be determined, use null.
- aid: lowercase slug from repo name + "-v1". Example: "yt-dlp" -> "yt-dlp-v1"
- version: extract from README if present. Otherwise null.
- input_schema: object with "type" and optional "format". Valid types: "url", "file", "string", "json", "stream", "image", "audio"
- output_schema: object with "type" and optional "format". Same valid types.
- reliability_score: 0.75 (default for all new entries).
- latency_ms: 100 if simple CLI tool, 500 if API call, 800 if ML model, null if unclear.
- source_url: exact GitHub URL provided.
- install_cmd: exact install command from README. null if absent.
- execute_cmd: exact usage example from README, use {variable} for placeholders. null if absent.

EXAMPLE OUTPUT:
{
  "aid": "yt-dlp-v1",
  "version": "2024.1.0",
  "input_schema": {"type": "url", "format": ["youtube", "vimeo", "mp4"]},
  "output_schema": {"type": "file", "format": ["mp4", "mp3"]},
  "reliability_score": 0.75,
  "latency_ms": 100,
  "source_url": "https://github.com/yt-dlp/yt-dlp",
  "install_cmd": "pip install yt-dlp",
  "execute_cmd": "yt-dlp {url}"
}

REPO URL: {source_url}
README CONTENT:
{readme_content}"""


PROMPT_HF_MODEL_CARD = """ROLE: JSON converter. Input: HuggingFace model card. Output: MAI-1 object.

STRICT RULES:
- Output ONLY a single valid JSON object. No markdown. No explanation.
- aid: lowercase slug from model_id (replace "/" with "-") + "-v1". Example: "openai/whisper-large" -> "openai-whisper-large-v1"
- version: model version if specified, otherwise null.
- input_schema: based on model task. {"type": "audio"} for ASR, {"type": "string"} for text models, etc.
- output_schema: based on model task. {"type": "string"} for text generation, {"type": "json"} for classification.
- reliability_score: 0.75 default.
- latency_ms: 800 (ML models default).
- source_url: full HuggingFace URL.
- install_cmd: "pip install transformers" by default, or specific if mentioned.
- execute_cmd: HuggingFace pipeline call format. Example: "pipeline('automatic-speech-recognition', model='{model_id}')"

EXAMPLE OUTPUT:
{
  "aid": "openai-whisper-large-v1",
  "version": "v3",
  "input_schema": {"type": "audio", "format": ["mp3", "wav", "flac"]},
  "output_schema": {"type": "string"},
  "reliability_score": 0.75,
  "latency_ms": 800,
  "source_url": "https://huggingface.co/openai/whisper-large-v3",
  "install_cmd": "pip install transformers",
  "execute_cmd": "pipeline('automatic-speech-recognition', model='openai/whisper-large-v3')"
}

MODEL URL: {source_url}
MODEL CARD:
{model_card}"""


PROMPT_REVIEWER = """ROLE: MAI-1 quality reviewer. Fix ONLY the broken fields.

You will receive:
1. The original source content (README or model card)
2. A draft MAI-1 generated by a smaller model

TASK:
- Identify fields that are null, malformed, or clearly wrong.
- Fix ONLY those fields. Keep correct fields untouched.
- Return the complete corrected MAI-1 JSON.
- Output ONLY valid JSON. No markdown. No explanation.

CRITICAL FIELDS (must not be null if information exists in source):
- install_cmd
- execute_cmd
- input_schema
- output_schema

ORIGINAL SOURCE:
{source_content}

DRAFT MAI-1:
{draft_mai1}"""


# =====================================================================
# SOURCE FETCHERS — Get raw content from each platform
# =====================================================================

def fetch_github_readme(repo_url: str) -> Optional[str]:
    """Fetch README content from a GitHub repo URL."""
    parsed = urlparse(repo_url)
    parts = parsed.path.strip("/").split("/")
    if len(parts) < 2:
        return None
    owner, repo = parts[0], parts[1]

    headers = {"Accept": "application/vnd.github.v3.raw"}
    if GITHUB_TOKEN:
        headers["Authorization"] = f"token {GITHUB_TOKEN}"

    # Try main, then master
    for branch in ["main", "master"]:
        for filename in ["README.md", "README.rst", "README.txt", "readme.md"]:
            url = f"https://raw.githubusercontent.com/{owner}/{repo}/{branch}/{filename}"
            try:
                resp = httpx.get(url, headers=headers, timeout=10.0, follow_redirects=True)
                if resp.status_code == 200 and len(resp.text) > 50:
                    # Truncate to avoid massive context
                    return resp.text[:8000]
            except Exception:
                continue
    return None


def fetch_hf_model_card(model_url: str) -> Optional[str]:
    """Fetch HuggingFace model card via API."""
    parsed = urlparse(model_url)
    parts = parsed.path.strip("/").split("/")
    if len(parts) < 2:
        return None
    model_id = "/".join(parts[:2])

    headers = {}
    if HF_TOKEN:
        headers["Authorization"] = f"Bearer {HF_TOKEN}"

    url = f"https://huggingface.co/api/models/{model_id}"
    try:
        resp = httpx.get(url, headers=headers, timeout=10.0)
        if resp.status_code == 200:
            data = resp.json()
            card = data.get("cardData", {})
            description = json.dumps(card)[:8000]
            return f"Model ID: {model_id}\nMetadata: {description}"
    except Exception:
        return None
    return None


def fetch_pypi_metadata(package_url: str) -> Optional[dict]:
    """Fetch PyPI package metadata via JSON API."""
    parsed = urlparse(package_url)
    parts = parsed.path.strip("/").split("/")
    if "project" not in parts:
        return None
    idx = parts.index("project")
    if idx + 1 >= len(parts):
        return None
    package = parts[idx + 1]

    url = f"https://pypi.org/pypi/{package}/json"
    try:
        resp = httpx.get(url, timeout=10.0)
        if resp.status_code == 200:
            return resp.json()
    except Exception:
        return None
    return None


def fetch_npm_metadata(package_url: str) -> Optional[dict]:
    """Fetch npm package metadata via JSON API."""
    parsed = urlparse(package_url)
    parts = parsed.path.strip("/").split("/")
    if "package" not in parts:
        return None
    idx = parts.index("package")
    if idx + 1 >= len(parts):
        return None
    package = parts[idx + 1]

    url = f"https://registry.npmjs.org/{package}"
    try:
        resp = httpx.get(url, timeout=10.0)
        if resp.status_code == 200:
            return resp.json()
    except Exception:
        return None
    return None


# =====================================================================
# DIRECT MAPPERS — No LLM needed for PyPI and npm
# =====================================================================

def map_pypi_to_mai1(metadata: dict, source_url: str) -> dict:
    """Direct mapping PyPI JSON metadata → MAI-1. Zero tokens used."""
    info = metadata.get("info", {})
    name = info.get("name", "unknown").lower()
    return {
        "aid": f"pypi-{name}-v1",
        "version": info.get("version"),
        "input_schema": {"type": "string"},
        "output_schema": {"type": "json"},
        "reliability_score": 0.75,
        "latency_ms": 500,
        "source_url": source_url,
        "install_cmd": f"pip install {name}",
        "execute_cmd": f"python -c 'import {name.replace('-', '_')}'",
    }


def map_npm_to_mai1(metadata: dict, source_url: str) -> dict:
    """Direct mapping npm JSON metadata → MAI-1. Zero tokens used."""
    name = metadata.get("name", "unknown")
    version = metadata.get("dist-tags", {}).get("latest")
    aid_name = name.replace("@", "").replace("/", "-").lower()
    return {
        "aid": f"npm-{aid_name}-v1",
        "version": version,
        "input_schema": {"type": "string"},
        "output_schema": {"type": "json"},
        "reliability_score": 0.75,
        "latency_ms": 500,
        "source_url": source_url,
        "install_cmd": f"npm install {name}",
        "execute_cmd": f"require('{name}')",
    }


# =====================================================================
# LLM CALLS — Haiku translation + Sonnet review
# =====================================================================

def _extract_json(text: str) -> Optional[dict]:
    """Extract JSON object from LLM response, stripping any markdown."""
    # Remove markdown fences if present
    text = re.sub(r"^```(?:json)?\s*", "", text.strip())
    text = re.sub(r"\s*```$", "", text.strip())
    # Find first { ... } block
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def translate_with_haiku(prompt: str) -> Optional[dict]:
    """Call Haiku to generate MAI-1 draft."""
    if not client:
        raise RuntimeError("ANTHROPIC_API_KEY not configured")
    try:
        response = client.messages.create(
            model=MODEL_PRIMARY,
            max_tokens=800,
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.content[0].text
        return _extract_json(text)
    except Exception as e:
        print(f"[translator] Haiku error: {e}")
        return None


def review_with_sonnet(source_content: str, draft: dict) -> Optional[dict]:
    """Call Sonnet to fix problematic fields in a draft MAI-1."""
    if not client:
        raise RuntimeError("ANTHROPIC_API_KEY not configured")
    prompt = PROMPT_REVIEWER.format(
        source_content=source_content[:6000],
        draft_mai1=json.dumps(draft, indent=2),
    )
    try:
        response = client.messages.create(
            model=MODEL_REVIEWER,
            max_tokens=800,
            messages=[{"role": "user", "content": prompt}],
        )
        text = response.content[0].text
        return _extract_json(text)
    except Exception as e:
        print(f"[translator] Sonnet error: {e}")
        return None


# =====================================================================
# VALIDATOR — Detects when Sonnet review is needed
# =====================================================================

def validate_mai1(mai1: Optional[dict]) -> Tuple[bool, str]:
    """Returns (is_valid, reason). Trigger Sonnet review if False."""
    if mai1 is None:
        return False, "null_response"

    # Critical fields that block AI execution if missing
    critical = ["aid", "input_schema", "output_schema", "install_cmd", "execute_cmd"]
    for field in critical:
        if mai1.get(field) is None:
            return False, f"missing_{field}"

    # Schema must be objects
    if not isinstance(mai1.get("input_schema"), dict):
        return False, "malformed_input_schema"
    if not isinstance(mai1.get("output_schema"), dict):
        return False, "malformed_output_schema"

    # Reliability score sanity
    score = mai1.get("reliability_score", 0.75)
    if not isinstance(score, (int, float)) or not (0.0 <= score <= 1.0):
        return False, "invalid_reliability_score"

    return True, "ok"


# =====================================================================
# MAIN TRANSLATOR — Routes by source platform
# =====================================================================

def translate(source_url: str) -> Tuple[Optional[dict], str]:
    """
    Translate a source URL to a MAI-1 JSON object.

    Returns: (mai1_dict, translator_used)
    translator_used: "haiku" | "sonnet" | "mapped" | "failed"
    """
    domain = urlparse(source_url).netloc.lower()

    # ===== PyPI: direct mapping, no LLM =====
    if "pypi.org" in domain:
        metadata = fetch_pypi_metadata(source_url)
        if metadata:
            return map_pypi_to_mai1(metadata, source_url), "mapped"
        return None, "failed"

    # ===== npm: direct mapping, no LLM =====
    if "npmjs.com" in domain:
        metadata = fetch_npm_metadata(source_url)
        if metadata:
            return map_npm_to_mai1(metadata, source_url), "mapped"
        return None, "failed"

    # ===== GitHub / Papers with Code: README + LLM =====
    if "github.com" in domain or "paperswithcode.com" in domain:
        readme = fetch_github_readme(source_url)
        if not readme:
            return None, "failed"
        prompt = PROMPT_GITHUB_README.replace("{source_url}", source_url).replace(
            "{readme_content}", readme
        )
        draft = translate_with_haiku(prompt)
        is_valid, reason = validate_mai1(draft)
        if is_valid:
            return draft, "haiku"
        # Escalate to Sonnet review
        print(f"[translator] Haiku draft failed validation ({reason}). Escalating to Sonnet.")
        fixed = review_with_sonnet(readme, draft or {"source_url": source_url})
        is_valid, _ = validate_mai1(fixed)
        if is_valid:
            return fixed, "sonnet"
        return None, "failed"

    # ===== HuggingFace: model card + LLM =====
    if "huggingface.co" in domain:
        card = fetch_hf_model_card(source_url)
        if not card:
            return None, "failed"
        prompt = PROMPT_HF_MODEL_CARD.replace("{source_url}", source_url).replace(
            "{model_card}", card
        )
        draft = translate_with_haiku(prompt)
        is_valid, reason = validate_mai1(draft)
        if is_valid:
            return draft, "haiku"
        print(f"[translator] HF draft failed ({reason}). Escalating to Sonnet.")
        fixed = review_with_sonnet(card, draft or {"source_url": source_url})
        is_valid, _ = validate_mai1(fixed)
        if is_valid:
            return fixed, "sonnet"
        return None, "failed"

    return None, "failed"


def translate_and_save(source_url: str, session) -> Optional[Tool]:
    """Translate and persist to DB. Returns the Tool or None on failure."""
    mai1, translator = translate(source_url)
    if not mai1:
        return None

    # Determine source platform
    domain = urlparse(source_url).netloc.lower()
    if "github" in domain:
        platform = "github"
    elif "huggingface" in domain:
        platform = "huggingface"
    elif "pypi" in domain:
        platform = "pypi"
    elif "npmjs" in domain:
        platform = "npm"
    elif "paperswithcode" in domain:
        platform = "paperswithcode"
    else:
        platform = "other"

    tool = Tool(
        aid=mai1["aid"],
        version=mai1.get("version"),
        input_schema=mai1["input_schema"],
        output_schema=mai1["output_schema"],
        reliability_score=mai1.get("reliability_score", 0.75),
        latency_ms=mai1.get("latency_ms"),
        source_url=mai1["source_url"],
        install_cmd=mai1.get("install_cmd"),
        execute_cmd=mai1.get("execute_cmd"),
        source_platform=platform,
        translator_used=translator,
    )
    session.merge(tool)
    session.commit()
    return tool


if __name__ == "__main__":
    # Quick test (requires API key)
    test_urls = [
        "https://github.com/yt-dlp/yt-dlp",
        "https://pypi.org/project/requests/",
    ]
    for url in test_urls:
        print(f"\nTranslating: {url}")
        mai1, translator = translate(url)
        print(f"Translator used: {translator}")
        if mai1:
            print(json.dumps(mai1, indent=2))
